import Flutter
import UIKit

/// iOS implementation of the `carp_debug_flutter` native bridge.
///
/// The toolkit only delegates to native code for things that genuinely require
/// it: reading device / app metadata. Programmatic relaunch is not permitted on
/// iOS, so `restartApp` throws and the Dart side performs an in-process restart.
///
/// All wiring (channel names, serialization) is generated by Pigeon in
/// `Messages.g.swift`; this class just conforms to the generated
/// `CarpDebugHostApi` protocol.
public class CarpDebugFlutterPlugin: NSObject, FlutterPlugin, CarpDebugHostApi {
  /// Registers the plugin and binds it to the Pigeon-generated channel.
  public static func register(with registrar: FlutterPluginRegistrar) {
    let instance = CarpDebugFlutterPlugin()
    CarpDebugHostApiSetup.setUp(
      binaryMessenger: registrar.messenger(), api: instance)
  }

  /// Collects device and application metadata from `UIDevice` and the main
  /// `Bundle`.
  func getDeviceInfo() throws -> NativeDeviceInfo {
    let device = UIDevice.current
    let bundle = Bundle.main
    return NativeDeviceInfo(
      platform: "iOS",
      osVersion: device.systemVersion,
      deviceModel: CarpDebugFlutterPlugin.hardwareIdentifier(),
      deviceName: device.name,
      isPhysicalDevice: CarpDebugFlutterPlugin.isPhysicalDevice(),
      appName: bundle.displayName,
      packageName: bundle.bundleIdentifier,
      appVersion: bundle.string(for: "CFBundleShortVersionString"),
      buildNumber: bundle.string(for: "CFBundleVersion")
    )
  }

  /// iOS forbids relaunching the process programmatically (it is grounds for
  /// App Store rejection), so we signal "unsupported" and let Dart fall back to
  /// an in-process restart of the widget tree.
  func restartApp() throws -> Bool {
    throw PigeonError(
      code: "unsupported",
      message: "Programmatic relaunch is not supported on iOS.",
      details: "The toolkit falls back to an in-process Dart restart.")
  }

  // MARK: - Helpers

  /// The hardware model identifier, e.g. `iPhone15,2`. Falls back to the
  /// `UIDevice.model` family name if the low-level lookup fails.
  private static func hardwareIdentifier() -> String {
    var systemInfo = utsname()
    uname(&systemInfo)
    let machine = Mirror(reflecting: systemInfo.machine).children
      .compactMap { ($0.value as? Int8).flatMap { $0 != 0 ? $0 : nil } }
      .map { String(UnicodeScalar(UInt8($0))) }
      .joined()
    return machine.isEmpty ? UIDevice.current.model : machine
  }

  /// `false` when running under the iOS Simulator, `true` on real hardware.
  private static func isPhysicalDevice() -> Bool {
    #if targetEnvironment(simulator)
      return false
    #else
      return true
    #endif
  }
}

/// Convenience accessors for values stored in the app's `Info.plist`.
private extension Bundle {
  /// The user-visible app name, preferring the display name over the bundle
  /// name.
  var displayName: String? {
    string(for: "CFBundleDisplayName") ?? string(for: "CFBundleName")
  }

  /// Reads a `String` value for [key] from the bundle's info dictionary.
  func string(for key: String) -> String? {
    object(forInfoDictionaryKey: key) as? String
  }
}
