// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Read-only snapshot of device and application metadata, collected natively.
///
/// Surfaced by the "Device & App" tool so a tester can confirm exactly which
/// build, OS and hardware they are looking at.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeDeviceInfo: Hashable, CustomStringConvertible {
  /// `iOS` or `Android`.
  var platform: String
  /// Operating-system version string, e.g. `17.4` or `14`.
  var osVersion: String? = nil
  /// Marketing / internal hardware model identifier.
  var deviceModel: String? = nil
  /// User-visible device name (iOS) or product name (Android).
  var deviceName: String? = nil
  /// `false` when running on a simulator / emulator, `true` on real hardware.
  var isPhysicalDevice: Bool? = nil
  /// Display name of the host application.
  var appName: String? = nil
  /// Bundle identifier (iOS) / application id (Android).
  var packageName: String? = nil
  /// Marketing version, e.g. `2.1.0`.
  var appVersion: String? = nil
  /// Build number, e.g. `42`.
  var buildNumber: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeDeviceInfo? {
    let platform = pigeonVar_list[0] as! String
    let osVersion: String? = nilOrValue(pigeonVar_list[1])
    let deviceModel: String? = nilOrValue(pigeonVar_list[2])
    let deviceName: String? = nilOrValue(pigeonVar_list[3])
    let isPhysicalDevice: Bool? = nilOrValue(pigeonVar_list[4])
    let appName: String? = nilOrValue(pigeonVar_list[5])
    let packageName: String? = nilOrValue(pigeonVar_list[6])
    let appVersion: String? = nilOrValue(pigeonVar_list[7])
    let buildNumber: String? = nilOrValue(pigeonVar_list[8])

    return NativeDeviceInfo(
      platform: platform,
      osVersion: osVersion,
      deviceModel: deviceModel,
      deviceName: deviceName,
      isPhysicalDevice: isPhysicalDevice,
      appName: appName,
      packageName: packageName,
      appVersion: appVersion,
      buildNumber: buildNumber
    )
  }
  func toList() -> [Any?] {
    return [
      platform,
      osVersion,
      deviceModel,
      deviceName,
      isPhysicalDevice,
      appName,
      packageName,
      appVersion,
      buildNumber,
    ]
  }
  static func == (lhs: NativeDeviceInfo, rhs: NativeDeviceInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.platform, rhs.platform) && MessagesPigeonInternal.deepEquals(lhs.osVersion, rhs.osVersion) && MessagesPigeonInternal.deepEquals(lhs.deviceModel, rhs.deviceModel) && MessagesPigeonInternal.deepEquals(lhs.deviceName, rhs.deviceName) && MessagesPigeonInternal.deepEquals(lhs.isPhysicalDevice, rhs.isPhysicalDevice) && MessagesPigeonInternal.deepEquals(lhs.appName, rhs.appName) && MessagesPigeonInternal.deepEquals(lhs.packageName, rhs.packageName) && MessagesPigeonInternal.deepEquals(lhs.appVersion, rhs.appVersion) && MessagesPigeonInternal.deepEquals(lhs.buildNumber, rhs.buildNumber)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeDeviceInfo")
    MessagesPigeonInternal.deepHash(value: platform, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: osVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deviceModel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deviceName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isPhysicalDevice, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: appName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: packageName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: appVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: buildNumber, hasher: &hasher)
  }

  public var description: String {
    return "NativeDeviceInfo(platform: \(String(describing: platform)), osVersion: \(String(describing: osVersion)), deviceModel: \(String(describing: deviceModel)), deviceName: \(String(describing: deviceName)), isPhysicalDevice: \(String(describing: isPhysicalDevice)), appName: \(String(describing: appName)), packageName: \(String(describing: packageName)), appVersion: \(String(describing: appVersion)), buildNumber: \(String(describing: buildNumber)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeDeviceInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeDeviceInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Native capabilities invoked from Dart.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CarpDebugHostApi {
  /// Collects [NativeDeviceInfo] from the platform.
  func getDeviceInfo() throws -> NativeDeviceInfo
  /// Relaunches the host application from scratch.
  ///
  /// Returns `true` when a relaunch was initiated. Throws on platforms that do
  /// not support programmatic relaunch (notably iOS, where the toolkit falls
  /// back to an in-process Dart restart).
  func restartApp() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CarpDebugHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `CarpDebugHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CarpDebugHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Collects [NativeDeviceInfo] from the platform.
    let getDeviceInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.carp_debug_flutter.CarpDebugHostApi.getDeviceInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeviceInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeviceInfoChannel.setMessageHandler(nil)
    }
    /// Relaunches the host application from scratch.
    ///
    /// Returns `true` when a relaunch was initiated. Throws on platforms that do
    /// not support programmatic relaunch (notably iOS, where the toolkit falls
    /// back to an in-process Dart restart).
    let restartAppChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.carp_debug_flutter.CarpDebugHostApi.restartApp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      restartAppChannel.setMessageHandler { _, reply in
        do {
          let result = try api.restartApp()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      restartAppChannel.setMessageHandler(nil)
    }
  }
}
