package dk.carp.carp_debug_flutter

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.os.Build
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.embedding.engine.plugins.activity.ActivityAware
import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding
import kotlin.system.exitProcess

/**
 * Android implementation of the `carp_debug_flutter` native bridge.
 *
 * The toolkit only delegates to native code for things that genuinely require
 * it: reading device / app metadata and relaunching the process. All channel
 * wiring is generated by Pigeon in `Messages.g.kt`; this class simply
 * implements the generated [CarpDebugHostApi] interface.
 *
 * Implements [ActivityAware] so [restartApp] can finish the current activity
 * before relaunching.
 */
class CarpDebugFlutterPlugin :
    FlutterPlugin,
    ActivityAware,
    CarpDebugHostApi {
    private var context: Context? = null
    private var activity: Activity? = null

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        context = binding.applicationContext
        CarpDebugHostApi.setUp(binding.binaryMessenger, this)
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        CarpDebugHostApi.setUp(binding.binaryMessenger, null)
        context = null
    }

    override fun onAttachedToActivity(binding: ActivityPluginBinding) {
        activity = binding.activity
    }

    override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
        activity = binding.activity
    }

    override fun onDetachedFromActivity() {
        activity = null
    }

    override fun onDetachedFromActivityForConfigChanges() {
        activity = null
    }

    /** Collects device and application metadata from [Build] and the package manager. */
    override fun getDeviceInfo(): NativeDeviceInfo {
        val ctx = requireNotNull(context) { "Plugin not attached to engine" }
        val pm = ctx.packageManager
        val packageName = ctx.packageName
        val info = pm.getPackageInfo(packageName, 0)
        val build =
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                info.longVersionCode.toString()
            } else {
                @Suppress("DEPRECATION")
                info.versionCode.toString()
            }
        return NativeDeviceInfo(
            platform = "Android",
            osVersion = Build.VERSION.RELEASE,
            deviceModel = "${Build.MANUFACTURER} ${Build.MODEL}",
            deviceName = Build.PRODUCT,
            isPhysicalDevice = !isProbablyEmulator(),
            appName = pm.getApplicationLabel(ctx.applicationInfo).toString(),
            packageName = packageName,
            appVersion = info.versionName,
            buildNumber = build,
        )
    }

    /**
     * Relaunches the app by starting a fresh instance of its launch activity in
     * a new, cleared task and then terminating the current process. Returns
     * `false` if no launch intent is available.
     */
    override fun restartApp(): Boolean {
        val ctx = context ?: return false
        val intent =
            ctx.packageManager.getLaunchIntentForPackage(ctx.packageName) ?: return false
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK)
        // Capture a stable reference; the field may be nulled if the activity
        // detaches while this method runs.
        val currentActivity = activity
        ctx.startActivity(intent)
        currentActivity?.finish()
        // Give the ActivityManager a moment to queue the new task before this
        // process is killed (avoids a relaunch race on slow devices).
        Thread.sleep(250)
        exitProcess(0)
    }

    /** Heuristic check for common emulator fingerprints. */
    private fun isProbablyEmulator(): Boolean =
        Build.FINGERPRINT.startsWith("generic") ||
            Build.FINGERPRINT.lowercase().contains("emulator") ||
            Build.MODEL.contains("Emulator") ||
            Build.MODEL.contains("Android SDK built for") ||
            Build.MANUFACTURER.contains("Genymotion") ||
            Build.PRODUCT.contains("sdk") ||
            Build.HARDWARE.contains("goldfish") ||
            Build.HARDWARE.contains("ranchu")
}
