// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dk.carp.carp_debug_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Read-only snapshot of device and application metadata, collected natively.
 *
 * Surfaced by the "Device & App" tool so a tester can confirm exactly which
 * build, OS and hardware they are looking at.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeDeviceInfo (
  /** `iOS` or `Android`. */
  val platform: String,
  /** Operating-system version string, e.g. `17.4` or `14`. */
  val osVersion: String? = null,
  /** Marketing / internal hardware model identifier. */
  val deviceModel: String? = null,
  /** User-visible device name (iOS) or product name (Android). */
  val deviceName: String? = null,
  /** `false` when running on a simulator / emulator, `true` on real hardware. */
  val isPhysicalDevice: Boolean? = null,
  /** Display name of the host application. */
  val appName: String? = null,
  /** Bundle identifier (iOS) / application id (Android). */
  val packageName: String? = null,
  /** Marketing version, e.g. `2.1.0`. */
  val appVersion: String? = null,
  /** Build number, e.g. `42`. */
  val buildNumber: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeDeviceInfo {
      val platform = pigeonVar_list[0] as String
      val osVersion = pigeonVar_list[1] as String?
      val deviceModel = pigeonVar_list[2] as String?
      val deviceName = pigeonVar_list[3] as String?
      val isPhysicalDevice = pigeonVar_list[4] as Boolean?
      val appName = pigeonVar_list[5] as String?
      val packageName = pigeonVar_list[6] as String?
      val appVersion = pigeonVar_list[7] as String?
      val buildNumber = pigeonVar_list[8] as String?
      return NativeDeviceInfo(platform, osVersion, deviceModel, deviceName, isPhysicalDevice, appName, packageName, appVersion, buildNumber)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      platform,
      osVersion,
      deviceModel,
      deviceName,
      isPhysicalDevice,
      appName,
      packageName,
      appVersion,
      buildNumber,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeDeviceInfo
    return MessagesPigeonUtils.deepEquals(this.platform, other.platform) && MessagesPigeonUtils.deepEquals(this.osVersion, other.osVersion) && MessagesPigeonUtils.deepEquals(this.deviceModel, other.deviceModel) && MessagesPigeonUtils.deepEquals(this.deviceName, other.deviceName) && MessagesPigeonUtils.deepEquals(this.isPhysicalDevice, other.isPhysicalDevice) && MessagesPigeonUtils.deepEquals(this.appName, other.appName) && MessagesPigeonUtils.deepEquals(this.packageName, other.packageName) && MessagesPigeonUtils.deepEquals(this.appVersion, other.appVersion) && MessagesPigeonUtils.deepEquals(this.buildNumber, other.buildNumber)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.platform)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.osVersion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceModel)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isPhysicalDevice)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.packageName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appVersion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.buildNumber)
    return result
  }
  override fun toString(): String {
    return "NativeDeviceInfo(platform=$platform, osVersion=$osVersion, deviceModel=$deviceModel, deviceName=$deviceName, isPhysicalDevice=$isPhysicalDevice, appName=$appName, packageName=$packageName, appVersion=$appVersion, buildNumber=$buildNumber)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeDeviceInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeDeviceInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Native capabilities invoked from Dart.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface CarpDebugHostApi {
  /** Collects [NativeDeviceInfo] from the platform. */
  fun getDeviceInfo(): NativeDeviceInfo
  /**
   * Relaunches the host application from scratch.
   *
   * Returns `true` when a relaunch was initiated. Throws on platforms that do
   * not support programmatic relaunch (notably iOS, where the toolkit falls
   * back to an in-process Dart restart).
   */
  fun restartApp(): Boolean

  companion object {
    /** The codec used by CarpDebugHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `CarpDebugHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CarpDebugHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.carp_debug_flutter.CarpDebugHostApi.getDeviceInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDeviceInfo())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.carp_debug_flutter.CarpDebugHostApi.restartApp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.restartApp())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
