// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Read-only snapshot of device and application metadata, collected natively.
///
/// Surfaced by the "Device & App" tool so a tester can confirm exactly which
/// build, OS and hardware they are looking at.
class NativeDeviceInfo {
  NativeDeviceInfo({
    required this.platform,
    this.osVersion,
    this.deviceModel,
    this.deviceName,
    this.isPhysicalDevice,
    this.appName,
    this.packageName,
    this.appVersion,
    this.buildNumber,
  });

  /// `iOS` or `Android`.
  String platform;

  /// Operating-system version string, e.g. `17.4` or `14`.
  String? osVersion;

  /// Marketing / internal hardware model identifier.
  String? deviceModel;

  /// User-visible device name (iOS) or product name (Android).
  String? deviceName;

  /// `false` when running on a simulator / emulator, `true` on real hardware.
  bool? isPhysicalDevice;

  /// Display name of the host application.
  String? appName;

  /// Bundle identifier (iOS) / application id (Android).
  String? packageName;

  /// Marketing version, e.g. `2.1.0`.
  String? appVersion;

  /// Build number, e.g. `42`.
  String? buildNumber;

  List<Object?> _toList() {
    return <Object?>[
      platform,
      osVersion,
      deviceModel,
      deviceName,
      isPhysicalDevice,
      appName,
      packageName,
      appVersion,
      buildNumber,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeDeviceInfo decode(Object result) {
    result as List<Object?>;
    return NativeDeviceInfo(
      platform: result[0]! as String,
      osVersion: result[1] as String?,
      deviceModel: result[2] as String?,
      deviceName: result[3] as String?,
      isPhysicalDevice: result[4] as bool?,
      appName: result[5] as String?,
      packageName: result[6] as String?,
      appVersion: result[7] as String?,
      buildNumber: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeDeviceInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(platform, other.platform) &&
        _deepEquals(osVersion, other.osVersion) &&
        _deepEquals(deviceModel, other.deviceModel) &&
        _deepEquals(deviceName, other.deviceName) &&
        _deepEquals(isPhysicalDevice, other.isPhysicalDevice) &&
        _deepEquals(appName, other.appName) &&
        _deepEquals(packageName, other.packageName) &&
        _deepEquals(appVersion, other.appVersion) &&
        _deepEquals(buildNumber, other.buildNumber);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeDeviceInfo(platform: $platform, osVersion: $osVersion, deviceModel: $deviceModel, deviceName: $deviceName, isPhysicalDevice: $isPhysicalDevice, appName: $appName, packageName: $packageName, appVersion: $appVersion, buildNumber: $buildNumber)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativeDeviceInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeDeviceInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Native capabilities invoked from Dart.
class CarpDebugHostApi {
  /// Constructor for [CarpDebugHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CarpDebugHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Collects [NativeDeviceInfo] from the platform.
  Future<NativeDeviceInfo> getDeviceInfo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.carp_debug_flutter.CarpDebugHostApi.getDeviceInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeDeviceInfo;
  }

  /// Relaunches the host application from scratch.
  ///
  /// Returns `true` when a relaunch was initiated. Throws on platforms that do
  /// not support programmatic relaunch (notably iOS, where the toolkit falls
  /// back to an in-process Dart restart).
  Future<bool> restartApp() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.carp_debug_flutter.CarpDebugHostApi.restartApp$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}
